(() => {
  'use strict'; const C=window.FatemehCore; const $=id=>document.getElementById(id); let adminOK=false;
  function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
  function status({text,mode}){const e=$('liveStatus');e.textContent=text;e.className='live-pill '+mode}
  const store=C.createStore({role:'partner',onChange:render,onStatus:status});
  async function verify(s){const creds=store.getCreds(); if(!creds?.admin||!s.adminHash){adminOK=false;return;} try{adminOK=(await C.sha256(creds.admin))===s.adminHash}catch{adminOK=false}}
  const moodMap={low:'😔 کم‌انرژی',neutral:'😐 معمولی',good:'🙂 خوب',great:'😍 عالی'};
  async function render(s){await verify(s); const lvl=C.levelInfo(s.wallet.lifetimeXp),done=s.daily.tasks.filter(t=>t.done).length;$('balance').textContent=C.formatNumber(s.wallet.balance);$('lifetime').textContent=C.formatNumber(s.wallet.lifetimeXp);$('level').textContent=`Level ${C.formatNumber(lvl.number)} · ${lvl.name} ${lvl.emoji}`;$('todayXp').textContent=C.formatNumber(s.daily.todayXp)+' XP';$('streak').textContent=C.formatNumber(s.streak.count);$('taskStat').textContent=`${C.formatNumber(done)} / ${C.formatNumber(s.daily.tasks.length)}`;$('mood').textContent=moodMap[s.daily.mood]||'ثبت نشده';$('partnerMessage').value=s.daily.partnerMessage||'';
    $('taskList').innerHTML=s.daily.tasks.map(t=>`<div class="task ${t.done?'done':''}"><div class="task-check" style="cursor:default">${t.done?'✓':''}</div><div class="task-main"><div class="task-title">${C.escapeHtml(t.title)}</div></div><span class="xp-badge">${t.done?'انجام شد':`+${C.formatNumber(t.xp)} XP`}</span></div>`).join('')||'<div class="empty">ماموریتی نیست</div>';
    $('rewardList').innerHTML=s.rewards.map(r=>`<article class="reward"><div class="reward-icon">${C.escapeHtml(r.emoji||'🎁')}</div><h3>${C.escapeHtml(r.title)}</h3><p>${C.escapeHtml(r.description||'')}</p><div class="reward-bottom"><span class="cost">${C.formatNumber(r.cost)} XP</span><button class="btn btn-small btn-danger" data-del-reward="${C.escapeHtml(r.id)}">حذف</button></div></article>`).join('');
    $('history').innerHTML=s.history.length?s.history.slice(0,14).map(h=>`<div class="history-row"><div><div class="history-title">${C.escapeHtml(h.label)}</div><div class="history-time">${C.formatTime(h.at)}</div></div><div class="delta ${h.delta>=0?'plus':'minus'}">${h.delta>=0?'+':'−'}${C.formatNumber(Math.abs(h.delta))} XP</div></div>`).join(''):'<div class="empty">هنوز فعالیتی ثبت نشده</div>';
    $('lockedCard').classList.toggle('hidden',adminOK||!store.getCreds());$('adminArea').classList.toggle('hidden',!adminOK);$('notConnected').classList.toggle('hidden',!!store.getCreds()); const creds=store.getCreds(); if(creds){$('learnerLink').textContent=C.buildUrl('index.html',creds,false)}
  }
  async function adjust(delta,reason){if(!adminOK)return toast('دسترسی مدیریت تایید نشده');await store.mutate(s=>C.adminAdjust(s,delta,reason||'تشویق از طرف همراه'));toast('امتیاز همان لحظه به‌روزرسانی شد ✨')}
  document.querySelector('.quick-adjust').addEventListener('click',e=>{const b=e.target.closest('[data-delta]');if(b)adjust(Number(b.dataset.delta),Number(b.dataset.delta)>0?'امتیاز تشویقی 💜':'اصلاح موجودی')});
  $('applyAdjust').addEventListener('click',()=>{const d=Number($('customDelta').value),r=$('adjustReason').value.trim();if(!d)return toast('یک عدد وارد کن');adjust(d,r||'تغییر امتیاز');$('customDelta').value='';});
  $('saveMessage').addEventListener('click',async()=>{const m=$('partnerMessage').value.trim();await store.mutate(s=>{s.daily.partnerMessage=m});toast('پیام روی صفحه فاطمه رفت 💌')});
  $('addTask').addEventListener('click',async()=>{const title=$('taskTitle').value.trim(),xp=Math.max(5,Math.min(200,Number($('taskXp').value)||20));if(!title)return toast('عنوان ماموریت رو بنویس');await store.mutate(s=>s.daily.tasks.push({id:C.uid('task'),title,xp,done:false}));$('taskTitle').value='';toast('ماموریت اضافه شد 🎯')});
  $('addReward').addEventListener('click',async()=>{const title=$('rewardTitle').value.trim(),cost=Math.max(10,Number($('rewardCost').value)||100),emoji=$('rewardEmoji').value.trim()||'🎁',description=$('rewardDesc').value.trim();if(!title)return toast('اسم جایزه رو بنویس');await store.mutate(s=>s.rewards.push({id:C.uid('reward'),title,cost,emoji,description}));$('rewardTitle').value='';$('rewardDesc').value='';toast('جایزه به فروشگاه اضافه شد 🎁')});
  $('rewardList').addEventListener('click',async e=>{const b=e.target.closest('[data-del-reward]');if(!b)return;if(!confirm('این جایزه حذف بشه؟'))return;await store.mutate(s=>{s.rewards=s.rewards.filter(r=>r.id!==b.dataset.delReward)});toast('حذف شد')});
  $('shareLearner').addEventListener('click',async()=>{const creds=store.getCreds();if(!creds)return;const url=C.buildUrl('index.html',creds,false);if(navigator.share){try{await navigator.share({title:'قدم‌های فاطمه',text:'این لینک مخصوص اپ خودته ✨',url});return}catch{}}try{await navigator.clipboard.writeText(url);toast('لینک کپی شد')}catch{toast('لینک پایین صفحه آماده‌ست')}});
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{}); store.init();
})();
