(() => {
 const $=s=>document.querySelector(s), KEY='fatemehRewardStateV3', ROOM_KEY='fatemehRewardRoomV3';
 const today=()=>new Date().toISOString().slice(0,10);
 const rewards=[{xp:50,title:'قهوه ☕'},{xp:100,title:'فیلم 🎬'},{xp:180,title:'هدیه 🎁'},{xp:300,title:'قرار ویژه 💜'}];
 const levels=[{min:0,max:50,name:'شروع قشنگ'},{min:50,max:120,name:'روی موج'},{min:120,max:220,name:'مصمم'},{min:220,max:360,name:'درخشان'},{min:360,max:999999,name:'فوق‌العاده'}];
 const defaultTasks=[{id:'learn30',title:'۳۰ دقیقه آموزش'},{id:'practice',title:'تمرین چیزی که یاد گرفتم'},{id:'career',title:'یک قدم برای کار بعدی'},{id:'selfcare',title:'یک کار خوب برای خودم'}];
 let state=null;
 function firebaseReady(){const c=window.FIREBASE_CONFIG||{};return c.apiKey&&c.databaseURL&&c.projectId}
 function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
 function local(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
 function render(s){state=s||local()||{totalXP:0,streak:0,history:{},customTasks:[]};const d=state.history?.[today()]||{done:{},xp:0};const tasks=[...defaultTasks,...(state.customTasks||[])],done=Object.values(d.done||{}).filter(Boolean).length;$('#pTotalXP').textContent=state.totalXP||0;$('#pTodayXP').textContent=`${d.xp||0} XP`;$('#pStreak').textContent=state.streak||0;$('#pDone').textContent=`${done} / ${tasks.length}`;$('#pLevel').textContent=(levels.find(l=>(state.totalXP||0)>=l.min&&(state.totalXP||0)<l.max)||levels.at(-1)).name;const nr=rewards.find(r=>(state.totalXP||0)<r.xp);$('#pReward').textContent=nr?`${Math.max(0,nr.xp-(state.totalXP||0))} XP`:'همه باز شد';$('#pUpdated').textContent=state.updatedAt?`آخرین تغییر: ${new Date(state.updatedAt).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}`:'هنوز داده‌ای نیست';$('#pTasks').innerHTML=tasks.map(t=>`<div class="task ${d.done?.[t.id]?'done':''}"><div class="task-check">${d.done?.[t.id]?'✓':''}</div><div class="task-main"><div class="task-title">${t.title}</div><div class="task-sub">${d.done?.[t.id]?'انجام شده':'هنوز انجام نشده'}</div></div></div>`).join('')}
 async function connect(){const room=$('#pRoomCode').value.trim().toUpperCase();localStorage.setItem(ROOM_KEY,room);if(!room||!firebaseReady()){render();$('#pCloudStatus').textContent='محلی';$('#pCloudStatus').classList.add('offline');return}try{await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-database-compat.js');if(!firebase.apps.length)firebase.initializeApp(window.FIREBASE_CONFIG);const ref=firebase.database().ref('rooms/'+room+'/state');$('#pCloudStatus').textContent='زنده';$('#pCloudStatus').classList.remove('offline');ref.on('value',snap=>{const v=snap.val();if(v)render(v)});}catch(e){console.error(e);$('#pCloudStatus').textContent='خطای اتصال';$('#pCloudStatus').classList.add('offline');render()}}
 $('#pRoomCode').value=localStorage.getItem(ROOM_KEY)||'';$('#pConnect').onclick=connect;render();if($('#pRoomCode').value)connect();
})();
