(() => {
  'use strict'; const C=window.FatemehCore; const $=id=>document.getElementById(id); let links=null;
  function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2400)}
  function randHex(bytes=24){const a=new Uint8Array(bytes);crypto.getRandomValues(a);return Array.from(a,b=>b.toString(16).padStart(2,'0')).join('')}
  const ready=C.configReady(); $('configNotice').className='notice '+(ready?'success':''); $('configNotice').textContent=ready?'config.js آماده است؛ می‌تونی فضای مشترک رو بسازی.':'اول config.js را با Project URL و Publishable key پر کن؛ بعد این صفحه را Refresh کن.'; $('createRoom').disabled=!ready;
  $('createRoom').addEventListener('click',async()=>{if(!C.configReady())return;const btn=$('createRoom');btn.disabled=true;btn.textContent='در حال ساخت…';try{const room=crypto.randomUUID(),key=randHex(20),admin=randHex(20),adminHash=await C.sha256(admin),state=C.baseState(adminHash);const client=C.makeClient(key);const {error}=await client.from('couple_progress').insert({room_id:room,room_key:key,state});if(error)throw error;const creds={room,key,admin};const learner=C.buildUrl('index.html',creds,false),partner=C.buildUrl('partner.html',creds,true);links={learner,partner};$('learnerLink').textContent=learner;$('partnerLink').textContent=partner;$('result').classList.remove('hidden');$('result').scrollIntoView({behavior:'smooth',block:'start'});btn.textContent='فضای مشترک ساخته شد ✅';}catch(e){console.error(e);toast('ساخت فضای مشترک خطا داد؛ SQL و config.js رو چک کن');btn.disabled=false;btn.textContent='دوباره تلاش کن';}});
  $('openPartner').addEventListener('click',()=>{if(links)location.href=links.partner});
  $('shareLearner').addEventListener('click',async()=>{if(!links)return;if(navigator.share){try{await navigator.share({title:'قدم‌های فاطمه',text:'این لینک مخصوص اپ توئه ✨',url:links.learner});return}catch{}}try{await navigator.clipboard.writeText(links.learner);toast('لینک فاطمه کپی شد')}catch{toast('لینک بالا آماده‌ست')}});
})();
